apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: sidecar-injector-webhook
webhooks:
  - name: sidecar-injector-webhook.default.svc.cluster.local
    clientConfig:
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURWekNDQWorZ0F3SUJBZ0lVUjNQaW1ZYlViOUpQVE5SVGt1VW02cks4elRNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0pqRWtNQ0lHQTFVRUF3d2JjMmxrWldOaGNpMXBibXBsWTNSdmNpMTNaV0pvYjI5clgyTmhNQ0FYRFRJeApNRFF5TURFMk5EYzFNbG9ZRHpJeU9UVXdNakF6TVRZME56VXlXakFtTVNRd0lnWURWUVFEREJ0emFXUmxZMkZ5CkxXbHVhbVZqZEc5eUxYZGxZbWh2YjJ0ZlkyRXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUsKQW9JQkFRRGE3ZlhFSDM5dlBIT3ZnaDg0Q2ZaUU9VaEh1cGRZTnovRTFVR2NJWlUwYURKclIxWkUzS1JyMnpxSwo4aWROeHYvSWRoSXgrT0Q4cUFhSnJnQy9iS2EwU0ZOL0dsWktORTFoeDk4OGdjZjRYSVpReG5FYUNSZ1BhdzkxCnJ2aGhGOEdkMmNadzltbWh1NWtJRGllZ3hyQUlQWHg3NDlkVFExdG5mWERoaCtmMzMwZG03THVlMDh0c0NiRnAKOGJtTXU5bTFXQWsxVWp6Q1c2Y1lvSlNzdGRTbVJoNTJZZWF2Z29ROVZ6SUx5VHpwdUh2dmNzREdkMW9RZzlaSApUM0J2cTdqZ1lhSHVaOTFubGtDSVY2WDNCYmUveHBJbG9TaG9Ga21lOWJZbDBHT29GeFViUWNFQXpyUFJKSEcrClRuS05tZjI2UUZNMm16THNSSUk1UHl5WWxuQW5BZ01CQUFHamV6QjVNQjBHQTFVZERnUVdCQlNQSmdrYkw0YUYKVkpsR3VlYUl5RkxRMWVuK016QWZCZ05WSFNNRUdEQVdnQlNQSmdrYkw0YUZWSmxHdWVhSXlGTFExZW4rTXpBUApCZ05WSFJNQkFmOEVCVEFEQVFIL01DWUdBMVVkRVFRZk1CMkNHM05wWkdWallYSXRhVzVxWldOMGIzSXRkMlZpCmFHOXZhMTlqWVRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQXBaeFFVQlZ2T3ozelRBeVdtUU02c2p5N05DNloKSFlycEtLdzZQbTZzZEI0eEtPWGkwdzVQQlp1SW9WNGdVYjVDV0x6cng0Nk4zK3BHSzJXcW9IUkFOUFo4UU1nUAphMUZJVGtGdTY4OERQNStUaTA2MzYrbTVSbXJ0T2xGMGo1UlJQYlRBVzN1VGRJR0pqQUNiRkhPUnorN2l3ZWVMCkdEclU4MDNCT0tiei85eTQyNXFTd1NVR3Eza3gva25ibjNvdEVZcU9Jcm9JTDlUc1RBN244UktqSWIzQWgxWm8KbFAwNjZ1U1dHUG1lRUk3djR1WnhpZkk2VWtpZjVzNkJpT0oySExuSjVTMHI3Ui9QNkFpZ1Brck9wQjZOTTV1dwpxM05hNjgrRlFQNTVIc0E4ejVvUkNqT2twQnpuZU1tL0R5TlA0M214UmlQK3E0YnNsendkazhDWmt3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
      service:
        name: sidecar-injector-webhook
        namespace: default
        port: 443
        path: "/mutate"
    failurePolicy: Ignore
    rules:
      - operations:
          - "CREATE"
        apiGroups:
          - ""
        apiVersions:
          - "v1"
        resources:
          - "pods"
    sideEffects: None
    admissionReviewVersions: ["v1beta1", "v1"]
